// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIRIS_labs.Data;

namespace PIRIS_labs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PIRIS_labs.Data.Entities.City", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Name");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Name = "Yerpolis"
                        },
                        new
                        {
                            Name = "Qexpolis"
                        },
                        new
                        {
                            Name = "Ijefbridge"
                        },
                        new
                        {
                            Name = "Zhexson"
                        },
                        new
                        {
                            Name = "Dekdale"
                        },
                        new
                        {
                            Name = "Purgh"
                        },
                        new
                        {
                            Name = "Jine"
                        },
                        new
                        {
                            Name = "Fleim"
                        },
                        new
                        {
                            Name = "Andville"
                        },
                        new
                        {
                            Name = "Enslens"
                        },
                        new
                        {
                            Name = "Bruusginia"
                        },
                        new
                        {
                            Name = "Vluddon"
                        },
                        new
                        {
                            Name = "Cluebridge"
                        },
                        new
                        {
                            Name = "Besding"
                        },
                        new
                        {
                            Name = "Keedlas"
                        },
                        new
                        {
                            Name = "Plando"
                        },
                        new
                        {
                            Name = "Breka"
                        },
                        new
                        {
                            Name = "Bison"
                        },
                        new
                        {
                            Name = "Andsas"
                        },
                        new
                        {
                            Name = "Encedon"
                        },
                        new
                        {
                            Name = "Shixrith"
                        },
                        new
                        {
                            Name = "Justin"
                        },
                        new
                        {
                            Name = "Flufield"
                        },
                        new
                        {
                            Name = "Zheanford"
                        },
                        new
                        {
                            Name = "Graepding"
                        },
                        new
                        {
                            Name = "Osheles"
                        },
                        new
                        {
                            Name = "Ephoni"
                        },
                        new
                        {
                            Name = "Streah"
                        },
                        new
                        {
                            Name = "Ingdence"
                        },
                        new
                        {
                            Name = "Amport"
                        },
                        new
                        {
                            Name = "Mucaster"
                        },
                        new
                        {
                            Name = "Shagas"
                        },
                        new
                        {
                            Name = "Qribert"
                        },
                        new
                        {
                            Name = "Khetmore"
                        },
                        new
                        {
                            Name = "Dorough"
                        },
                        new
                        {
                            Name = "Stranta"
                        },
                        new
                        {
                            Name = "Jeka"
                        },
                        new
                        {
                            Name = "Qesa"
                        },
                        new
                        {
                            Name = "Olislas"
                        },
                        new
                        {
                            Name = "Icofield"
                        });
                });

            modelBuilder.Entity("PIRIS_labs.Data.Entities.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualResidenceAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ActualResidenceCityName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisabilityName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HomePhoneNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("LiableForMilitaryService")
                        .HasColumnType("bit");

                    b.Property<bool>("Male")
                        .HasColumnType("bit");

                    b.Property<string>("MaritalStatusName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MobilePhoneNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("MonthlyIncome")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NationalityName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PassportIssuedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("PassportIssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PassportSeries")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Pensioner")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RegistrationCityName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WorkPlace")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("ActualResidenceCityName");

                    b.HasIndex("DisabilityName");

                    b.HasIndex("MaritalStatusName");

                    b.HasIndex("NationalityName");

                    b.HasIndex("RegistrationCityName");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PIRIS_labs.Data.Entities.Disability", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Name");

                    b.ToTable("Disabilities");

                    b.HasData(
                        new
                        {
                            Name = "Musculoskeletal System"
                        },
                        new
                        {
                            Name = "Special Senses and Speech"
                        },
                        new
                        {
                            Name = "Respiratory Disorders"
                        },
                        new
                        {
                            Name = "Cardiovascular System"
                        },
                        new
                        {
                            Name = "Digestive System"
                        },
                        new
                        {
                            Name = "Genitourinary Disorders"
                        },
                        new
                        {
                            Name = "Hematological Disorders"
                        },
                        new
                        {
                            Name = "Skin Disorders"
                        },
                        new
                        {
                            Name = "Endocrine Disorders"
                        },
                        new
                        {
                            Name = "Congenital Disorders that Affect Multiple Body Systems"
                        },
                        new
                        {
                            Name = "Neurological Disorders"
                        },
                        new
                        {
                            Name = "Mental Disorders"
                        },
                        new
                        {
                            Name = "Cancer (Malignant Neoplastic Diseases)"
                        },
                        new
                        {
                            Name = "Immune System Disorders"
                        });
                });

            modelBuilder.Entity("PIRIS_labs.Data.Entities.MaritalStatus", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Name");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Name = "Single"
                        },
                        new
                        {
                            Name = "Married"
                        },
                        new
                        {
                            Name = "Widowed"
                        },
                        new
                        {
                            Name = "Divorced"
                        },
                        new
                        {
                            Name = "Separated"
                        },
                        new
                        {
                            Name = "Registered partnership"
                        });
                });

            modelBuilder.Entity("PIRIS_labs.Data.Entities.Nationality", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Name");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Name = "Afghan"
                        },
                        new
                        {
                            Name = "Albanian"
                        },
                        new
                        {
                            Name = "Algerian"
                        },
                        new
                        {
                            Name = "American"
                        },
                        new
                        {
                            Name = "Andorran"
                        },
                        new
                        {
                            Name = "Angolan"
                        },
                        new
                        {
                            Name = "Anguillan"
                        },
                        new
                        {
                            Name = "Argentine"
                        },
                        new
                        {
                            Name = "Armenian"
                        },
                        new
                        {
                            Name = "Australian"
                        },
                        new
                        {
                            Name = "Austrian"
                        },
                        new
                        {
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Name = "Bahamian"
                        },
                        new
                        {
                            Name = "Bahraini"
                        },
                        new
                        {
                            Name = "Bangladeshi"
                        },
                        new
                        {
                            Name = "Barbadian"
                        },
                        new
                        {
                            Name = "Belarusian"
                        },
                        new
                        {
                            Name = "Belgian"
                        },
                        new
                        {
                            Name = "Belizean"
                        },
                        new
                        {
                            Name = "Beninese"
                        },
                        new
                        {
                            Name = "Bermudian"
                        },
                        new
                        {
                            Name = "Bhutanese"
                        },
                        new
                        {
                            Name = "Bolivian"
                        },
                        new
                        {
                            Name = "Botswanan"
                        },
                        new
                        {
                            Name = "Brazilian"
                        },
                        new
                        {
                            Name = "British"
                        },
                        new
                        {
                            Name = "British Virgin Islander"
                        },
                        new
                        {
                            Name = "Bruneian"
                        },
                        new
                        {
                            Name = "Bulgarian"
                        },
                        new
                        {
                            Name = "Burkinan"
                        },
                        new
                        {
                            Name = "Burmese"
                        },
                        new
                        {
                            Name = "Burundian"
                        },
                        new
                        {
                            Name = "Cambodian"
                        },
                        new
                        {
                            Name = "Cameroonian"
                        },
                        new
                        {
                            Name = "Canadian"
                        },
                        new
                        {
                            Name = "Cape Verdean"
                        },
                        new
                        {
                            Name = "Cayman Islander"
                        },
                        new
                        {
                            Name = "Central African"
                        },
                        new
                        {
                            Name = "Chadian"
                        },
                        new
                        {
                            Name = "Chilean"
                        },
                        new
                        {
                            Name = "Chinese"
                        },
                        new
                        {
                            Name = "Citizen of Antigua and Barbuda"
                        },
                        new
                        {
                            Name = "Citizen of Bosnia and Herzegovina"
                        },
                        new
                        {
                            Name = "Citizen of Guinea-Bissau"
                        },
                        new
                        {
                            Name = "Citizen of Kiribati"
                        },
                        new
                        {
                            Name = "Citizen of Seychelles"
                        },
                        new
                        {
                            Name = "Citizen of the Dominican Republic"
                        },
                        new
                        {
                            Name = "Citizen of Vanuatu"
                        },
                        new
                        {
                            Name = "Colombian"
                        },
                        new
                        {
                            Name = "Comoran"
                        },
                        new
                        {
                            Name = "Congolese (Congo)"
                        },
                        new
                        {
                            Name = "Congolese (DRC)"
                        },
                        new
                        {
                            Name = "Cook Islander"
                        },
                        new
                        {
                            Name = "Costa Rican"
                        },
                        new
                        {
                            Name = "Croatian"
                        },
                        new
                        {
                            Name = "Cuban"
                        },
                        new
                        {
                            Name = "Cymraes"
                        },
                        new
                        {
                            Name = "Cymro"
                        },
                        new
                        {
                            Name = "Cypriot"
                        },
                        new
                        {
                            Name = "Czech"
                        },
                        new
                        {
                            Name = "Danish"
                        },
                        new
                        {
                            Name = "Djiboutian"
                        },
                        new
                        {
                            Name = "Dominican"
                        },
                        new
                        {
                            Name = "Dutch"
                        },
                        new
                        {
                            Name = "East Timorese"
                        },
                        new
                        {
                            Name = "Ecuadorean"
                        },
                        new
                        {
                            Name = "Egyptian"
                        },
                        new
                        {
                            Name = "Emirati"
                        },
                        new
                        {
                            Name = "English"
                        },
                        new
                        {
                            Name = "Equatorial Guinean"
                        },
                        new
                        {
                            Name = "Eritrean"
                        },
                        new
                        {
                            Name = "Estonian"
                        },
                        new
                        {
                            Name = "Ethiopian"
                        },
                        new
                        {
                            Name = "Faroese"
                        },
                        new
                        {
                            Name = "Fijian"
                        },
                        new
                        {
                            Name = "Filipino"
                        },
                        new
                        {
                            Name = "Finnish"
                        },
                        new
                        {
                            Name = "French"
                        },
                        new
                        {
                            Name = "Gabonese"
                        },
                        new
                        {
                            Name = "Gambian"
                        },
                        new
                        {
                            Name = "Georgian"
                        },
                        new
                        {
                            Name = "German"
                        },
                        new
                        {
                            Name = "Ghanaian"
                        },
                        new
                        {
                            Name = "Gibraltarian"
                        },
                        new
                        {
                            Name = "Greek"
                        },
                        new
                        {
                            Name = "Greenlandic"
                        },
                        new
                        {
                            Name = "Grenadian"
                        },
                        new
                        {
                            Name = "Guamanian"
                        },
                        new
                        {
                            Name = "Guatemalan"
                        },
                        new
                        {
                            Name = "Guinean"
                        },
                        new
                        {
                            Name = "Guyanese"
                        },
                        new
                        {
                            Name = "Haitian"
                        },
                        new
                        {
                            Name = "Honduran"
                        },
                        new
                        {
                            Name = "Hong Konger"
                        },
                        new
                        {
                            Name = "Hungarian"
                        },
                        new
                        {
                            Name = "Icelandic"
                        },
                        new
                        {
                            Name = "Indian"
                        },
                        new
                        {
                            Name = "Indonesian"
                        },
                        new
                        {
                            Name = "Iranian"
                        },
                        new
                        {
                            Name = "Iraqi"
                        },
                        new
                        {
                            Name = "Irish"
                        },
                        new
                        {
                            Name = "Israeli"
                        },
                        new
                        {
                            Name = "Italian"
                        },
                        new
                        {
                            Name = "Ivorian"
                        },
                        new
                        {
                            Name = "Jamaican"
                        },
                        new
                        {
                            Name = "Japanese"
                        },
                        new
                        {
                            Name = "Jordanian"
                        },
                        new
                        {
                            Name = "Kazakh"
                        },
                        new
                        {
                            Name = "Kenyan"
                        },
                        new
                        {
                            Name = "Kittitian"
                        },
                        new
                        {
                            Name = "Kosovan"
                        },
                        new
                        {
                            Name = "Kuwaiti"
                        },
                        new
                        {
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            Name = "Lao"
                        },
                        new
                        {
                            Name = "Latvian"
                        },
                        new
                        {
                            Name = "Lebanese"
                        },
                        new
                        {
                            Name = "Liberian"
                        },
                        new
                        {
                            Name = "Libyan"
                        },
                        new
                        {
                            Name = "Liechtenstein citizen"
                        },
                        new
                        {
                            Name = "Lithuanian"
                        },
                        new
                        {
                            Name = "Luxembourger"
                        },
                        new
                        {
                            Name = "Macanese"
                        },
                        new
                        {
                            Name = "Macedonian"
                        },
                        new
                        {
                            Name = "Malagasy"
                        },
                        new
                        {
                            Name = "Malawian"
                        },
                        new
                        {
                            Name = "Malaysian"
                        },
                        new
                        {
                            Name = "Maldivian"
                        },
                        new
                        {
                            Name = "Malian"
                        },
                        new
                        {
                            Name = "Maltese"
                        },
                        new
                        {
                            Name = "Marshallese"
                        },
                        new
                        {
                            Name = "Martiniquais"
                        },
                        new
                        {
                            Name = "Mauritanian"
                        },
                        new
                        {
                            Name = "Mauritian"
                        },
                        new
                        {
                            Name = "Mexican"
                        },
                        new
                        {
                            Name = "Micronesian"
                        },
                        new
                        {
                            Name = "Moldovan"
                        },
                        new
                        {
                            Name = "Monegasque"
                        },
                        new
                        {
                            Name = "Mongolian"
                        },
                        new
                        {
                            Name = "Montenegrin"
                        },
                        new
                        {
                            Name = "Montserratian"
                        },
                        new
                        {
                            Name = "Moroccan"
                        },
                        new
                        {
                            Name = "Mosotho"
                        },
                        new
                        {
                            Name = "Mozambican"
                        },
                        new
                        {
                            Name = "Namibian"
                        },
                        new
                        {
                            Name = "Nauruan"
                        },
                        new
                        {
                            Name = "Nepalese"
                        },
                        new
                        {
                            Name = "New Zealander"
                        },
                        new
                        {
                            Name = "Nicaraguan"
                        },
                        new
                        {
                            Name = "Nigerian"
                        },
                        new
                        {
                            Name = "Nigerien"
                        },
                        new
                        {
                            Name = "Niuean"
                        },
                        new
                        {
                            Name = "North Korean"
                        },
                        new
                        {
                            Name = "Northern Irish"
                        },
                        new
                        {
                            Name = "Norwegian"
                        },
                        new
                        {
                            Name = "Omani"
                        },
                        new
                        {
                            Name = "Pakistani"
                        },
                        new
                        {
                            Name = "Palauan"
                        },
                        new
                        {
                            Name = "Palestinian"
                        },
                        new
                        {
                            Name = "Panamanian"
                        },
                        new
                        {
                            Name = "Papua New Guinean"
                        },
                        new
                        {
                            Name = "Paraguayan"
                        },
                        new
                        {
                            Name = "Peruvian"
                        },
                        new
                        {
                            Name = "Pitcairn Islander"
                        },
                        new
                        {
                            Name = "Polish"
                        },
                        new
                        {
                            Name = "Portuguese"
                        },
                        new
                        {
                            Name = "Prydeinig"
                        },
                        new
                        {
                            Name = "Puerto Rican"
                        },
                        new
                        {
                            Name = "Qatari"
                        },
                        new
                        {
                            Name = "Romanian"
                        },
                        new
                        {
                            Name = "Russian"
                        },
                        new
                        {
                            Name = "Rwandan"
                        },
                        new
                        {
                            Name = "Salvadorean"
                        },
                        new
                        {
                            Name = "Sammarinese"
                        },
                        new
                        {
                            Name = "Samoan"
                        },
                        new
                        {
                            Name = "Sao Tomean"
                        },
                        new
                        {
                            Name = "Saudi Arabian"
                        },
                        new
                        {
                            Name = "Scottish"
                        },
                        new
                        {
                            Name = "Senegalese"
                        },
                        new
                        {
                            Name = "Serbian"
                        },
                        new
                        {
                            Name = "Sierra Leonean"
                        },
                        new
                        {
                            Name = "Singaporean"
                        },
                        new
                        {
                            Name = "Slovak"
                        },
                        new
                        {
                            Name = "Slovenian"
                        },
                        new
                        {
                            Name = "Solomon Islander"
                        },
                        new
                        {
                            Name = "Somali"
                        },
                        new
                        {
                            Name = "South African"
                        },
                        new
                        {
                            Name = "South Korean"
                        },
                        new
                        {
                            Name = "South Sudanese"
                        },
                        new
                        {
                            Name = "Spanish"
                        },
                        new
                        {
                            Name = "Sri Lankan"
                        },
                        new
                        {
                            Name = "St Helenian"
                        },
                        new
                        {
                            Name = "St Lucian"
                        },
                        new
                        {
                            Name = "Stateless"
                        },
                        new
                        {
                            Name = "Sudanese"
                        },
                        new
                        {
                            Name = "Surinamese"
                        },
                        new
                        {
                            Name = "Swazi"
                        },
                        new
                        {
                            Name = "Swedish"
                        },
                        new
                        {
                            Name = "Swiss"
                        },
                        new
                        {
                            Name = "Syrian"
                        },
                        new
                        {
                            Name = "Taiwanese"
                        },
                        new
                        {
                            Name = "Tajik"
                        },
                        new
                        {
                            Name = "Tanzanian"
                        },
                        new
                        {
                            Name = "Thai"
                        },
                        new
                        {
                            Name = "Togolese"
                        },
                        new
                        {
                            Name = "Tongan"
                        },
                        new
                        {
                            Name = "Trinidadian"
                        },
                        new
                        {
                            Name = "Tristanian"
                        },
                        new
                        {
                            Name = "Tunisian"
                        },
                        new
                        {
                            Name = "Turkish"
                        },
                        new
                        {
                            Name = "Turkmen"
                        },
                        new
                        {
                            Name = "Turks and Caicos Islander"
                        },
                        new
                        {
                            Name = "Tuvaluan"
                        },
                        new
                        {
                            Name = "Ugandan"
                        },
                        new
                        {
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Name = "Uruguayan"
                        },
                        new
                        {
                            Name = "Uzbek"
                        },
                        new
                        {
                            Name = "Vatican citizen"
                        },
                        new
                        {
                            Name = "Venezuelan"
                        },
                        new
                        {
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Name = "Vincentian"
                        },
                        new
                        {
                            Name = "Wallisian"
                        },
                        new
                        {
                            Name = "Welsh"
                        },
                        new
                        {
                            Name = "Yemeni"
                        },
                        new
                        {
                            Name = "Zambian"
                        },
                        new
                        {
                            Name = "Zimbabwean"
                        });
                });

            modelBuilder.Entity("PIRIS_labs.Data.Entities.Client", b =>
                {
                    b.HasOne("PIRIS_labs.Data.Entities.City", "ActualResidenceCity")
                        .WithMany()
                        .HasForeignKey("ActualResidenceCityName");

                    b.HasOne("PIRIS_labs.Data.Entities.Disability", "Disability")
                        .WithMany()
                        .HasForeignKey("DisabilityName");

                    b.HasOne("PIRIS_labs.Data.Entities.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusName");

                    b.HasOne("PIRIS_labs.Data.Entities.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityName");

                    b.HasOne("PIRIS_labs.Data.Entities.City", "RegistrationCity")
                        .WithMany()
                        .HasForeignKey("RegistrationCityName");

                    b.Navigation("ActualResidenceCity");

                    b.Navigation("Disability");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Nationality");

                    b.Navigation("RegistrationCity");
                });
#pragma warning restore 612, 618
        }
    }
}
